DBO-19 Update Schema and Add DB Unit Tests
nathanielcaron/engg4000 pull request #23
Opened 2021-10-12 22:37 UTC by JoaoPontes98

I added a /Service/db to house our db files. In there is the updated schema along with a few unit tests for the db. I also added a dbLib.js file to handle the different connection strings and other potential db functions. I also refactored the db connection in app.js to use the dbLib.js file

There are also more unit tests to be made for the other collections. But I didn't make them since we still don't have a set-in-stone data model until after we have the final wireframing. I just thought to make the unit tests after that since I think it would be more work to make the tests now and then fix them later.

P.S. I had to disable a linting-check in db.test.js, because when checking for unique id's in mongoose, you do <Name>._id. The linter doesn't like it :/

2021-10-13 13:39 UTC, fredy20501 requested changes
See comments below.

2021-10-13 13:39 UTC, fredy20501 commented on Service/db/dbSchema.js
> +const Post = mongoose.model('Post', postSchema, 'Post');
You can remove this post schema since it is the same as the new message schema.

2021-10-13 13:39 UTC, fredy20501 commented on Service/db/db.test.js
> +});
This test might lead to some intermittent failures. For example, if 2 people create a new PR, the unit tests for both PRs will run at the same time within our GitHub Actions which means one of them might be checking for an empty collection at the same time as the other is adding stuff to it.

Instead of this test we could just check once in a while whether there is some residual stuff in the test db and manually clear it (and also try to figure out why they didn't get deleted).

2021-10-13 13:39 UTC, fredy20501 commented on Service/db/db.test.js
> +});
Since you are deleting the test data within the test, it means that if the test fails it will stop and not reach the delete command, leading to test data not being cleared.

Potential solution: Have a global list defined at the top of the file. Whenever a test creates a test user (immediately after the `.save()`), add their ID to the list. Then you can add a global `AfterEach` block where you remove things from the list and delete them. (The `AfterEach` block always runs even if the test fails so it would solve the issue). Note in the future there would have to be a list for each type of object (i.e., `User` & `Message`) since you need to know which collection to delete from.

2021-10-13 13:39 UTC, fredy20501 commented on Service/app.js
> +db.connectDev(); // change to db.connectProd() when appropriate
Here we should implement the `dev` vs `prod` logic by checking the `NODE_ENV` environment variable:
```js
if (ENV.NODE_ENV === 'production') {
  db.connectProd();
}
else {
  db.connectDev();
}
```
This will be a lot easier than manually changing this line of code when switching to production.

2021-10-13 13:59 UTC, fredy20501 commented on Service/db/dbLib.js
> +const prodConnectionString = `mongodb+srv://${ENV.DB_USER}:${ENV.DB_PASS}@cluster0.pa1un.mongodb.net/${ENV.DB_PROD_NAME}?retryWrites=true&w=majority`;
I just tried to run it locally and found a new issue: when you connect with Mongoos to a database with a name that doesn't exist, it creates a new database with that name. For example, since I didn't have the `DB_TEST_NAME` it resolved to `undefined` which meant that it created a new database called `undefined` in our MongoDB cluster. To prevent this issue we might want to add an extra check to make sure the name isn't `undefined`. Although this isn't a big issue to be fair.

2021-10-13 14:02 UTC, JoaoPontes98 commented
> Sorry, apparently I closed this PR by mistake. Don't know how that happened 🤷 😅

Hahaha np! And this is all amazing feedback, thanks! I'll get on the fixes later this week, depending on when I finish my OS assignment lol

2021-10-13 14:05 UTC, fredy20501 commented
Dammit, I did it again 🙄 oof.
Anyway, I know it looks like a lot so please do take your time. No rush! 😄

2021-10-17 23:59 UTC, nathanielcaron commented on Service/db/dbLib.js
> +const mongoose = require('mongoose');
If I understand correctly, this file is a collection of useful util functions for the database?

Could we rename it to `dbUtils.js`?
We could also move it to the utils folder unless you prefer keeping it with the other database stuff.
I'm totally ok with that.

2021-10-17 23:59 UTC, nathanielcaron commented
Great work @JoaoPontes98

2021-10-18 00:00 UTC, nathanielcaron approved these changes

2021-10-18 20:02 UTC, fredy20501 commented on Service/db/dbUtils.js
> +};
This function is pretty dangerous since it drops the current database so we should probably add some safety feature to prevent accidentally deleting our dev or prod db. 
Here's what I suggest:
- In the `closeDatabase` function, check to make sure the current database name is not the same as the dev/prod databases. (I believe you can get the current db name using `mongoose.connection.name`). If it is the same as the dev/prod db than we should probably throw an error and/or log it as an error.
- Rename the function to `deleteDatabase()` to clarify what it really does.

2021-10-19 02:49 UTC, JoaoPontes98 commented on Service/db/dbUtils.js
> +};
Yeah checking the names is a great idea for safety. I added the changes in the newest commit. The `deleteDatabase()` now checks for the dev and prod db names and throws an error if found. I tested the function and it successfully prevents deleting the prod/dev db's. I also added a `closeDatabase()` to allow closing dev/prod connections.

2021-10-19 02:55 UTC, nathanielcaron commented on Service/db/dbUtils.js
> +};
Very nice

2021-10-19 11:46 UTC, merged